### ISSUE TITLE
Placing a framed block on another framed block only works when sneaking

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PianoManu/BlockCarpentry#10]
When holding a framed block and right clicking on a second framed block, nothing happens. The framed block eats the right click action and no block is placed. I expected the framed block in my hand to be placed.

**Comment by PianoManu** [comment]
Thanks for reporting. I noticed that when testing, but I ignored it, as I thought it wouldn't be a big deal. I'll fix that ASAP.
Regards, Manu

**Comment by PianoManu** [comment]
I got it to work for some blocks right now, but I wont change that for beds, chests, fence gates, trapdoors, doors and buttons, because that's the same behaviour as their vanilla counterparts.
Regards, Manu

**Comment by PianoManu** [comment]
I tested it and it works quite fine now. Regards, Manu

**Comment by PianoManu** [comment]
I've tested it and did not notice any bugs concerning this issue anymore, so I marked this as fixed and will close this now
