### ISSUE TITLE
Breaking framed blocks in creative mode drops items

### ISSUE THREAD

**Issue by TheDeviantCrafter** [PianoManu/BlockCarpentry#11]
Breaking a framed block while in creative mode causes any block attached to it to drop. They should drop nothing.

**Comment by PianoManu** [comment]
Same reason as #9 
Will fix that when I have time

**Comment by PianoManu** [comment]
I have overcome myself and changed it this morning. I tested it in both survival and creative and it works fine now. I'll consider this as fixed and will close the issue now

**Comment by PianoManu** [comment]
I just noticed that it only do not drop the block if you use the hammer. For that, I check whether the player's gamemode is creative. But for the destroying-method (onReplaced), you don't have a player argument, so I can't do it this way. I'll leave it as it is, because it's not a big deal
