### ISSUE TITLE
BlockCarpentry does not work with Optifine (Work-around)

### ISSUE THREAD

**Issue by PianoManu** [PianoManu/BlockCarpentry#13]
Hey guys, since blocks from BlockCarpentry are invisible when optifine is installed, I've got an idea how to circumvent this problem. In the next version I'll add an entry to the config file, where you can enable or disable block opacity. When enabled, you can use Optifine together with BlockCarpentry, but blocks like glass wont be transparent anymore. When disabled (which will be the default value), glass, slime blocks, etc. will be transparent, but they wont be rendered when using optifine. I guess that will help for now. In the meantime I'll try to fix this problem. I've read some articles concerning this rendering issue, but as I'm pretty new to modding, I don't know if it's something I can solve myself, so I added the "help wanted" label. If you know how to fix it or if you can give me some hints or tips, I'll be very grateful!
Thanks in advance, Manu

**Comment by Lerizo** [comment]
So right now we have to wait for that version? Or you already did it?

**Comment by Blugori** [comment]
We have to wait !

**Comment by PianoManu** [comment]
As I said, I've made some sort of work-around, but I'm not really happy with it (most features would break), so I did not update yet. I asked for help at the forge forum, and someone said, it's a problem from the side of OptiFine, so I opened [an issue at the OptiFine repository](https://github.com/sp614x/optifine/issues/4920) some days ago and now I'm waiting for a response, whether this problem really is caused by OptiFine (then it might be something out of my control), or whether this problem is caused by BlockCarpentry. In the meantime, I'll think about how to improve the work-around. Thanks for your patience!
Regards, Manu

**Comment by PianoManu** [comment]
I found the problem and will fix it when I finish studying today

**Comment by PianoManu** [comment]
BlockCarpentry should work with OptiFine now in Version 0.3.4 for 1.16.2/1.16.3
I will back-port this fix to 1.16.1 and 1.15 soon

**Comment by PianoManu** [comment]
Does the issue still occur, when using Optifine together with BlockCarpentry 1.16.2/3 0.3.4?

**Comment by PianoManu** [comment]
I did not encounter this bug anymore, so I guess it really works

**Comment by PianoManu** [comment]
Oops linked the wrong issue... I meant to refer to #39 ... Idk how this happened
