### ISSUE TITLE
Tool Textures

### ISSUE THREAD

**Issue by WenXin20** [PianoManu/BlockCarpentry#15]
Hello, I made some new tool textures if you would like to take a look at them or use them for the mod.
[blockcarpentry_tools.zip](https://github.com/PianoManu/BlockCarpentry/files/5357037/blockcarpentry_tools.zip)
![chisel](https://user-images.githubusercontent.com/12000593/95622559-604ced80-0a39-11eb-9f62-0ddab2ce5376.png)![texture_wrench](https://user-images.githubusercontent.com/12000593/95622603-70fd6380-0a39-11eb-8cfd-118f56d2b7c4.png)![paintbrush](https://user-images.githubusercontent.com/12000593/95622593-6cd14600-0a39-11eb-8e5b-c0832bf29ed9.png)![hammer](https://user-images.githubusercontent.com/12000593/95622581-680c9200-0a39-11eb-9886-cc035ba0afb4.png)

**Comment by PianoManu** [comment]
Woah, they are beautiful, better than mine! I'm not a good artist ^^
Thank you very much! I'll add them in the next update

**Comment by WenXin20** [comment]
No problem, I'm glad you like them!
