### ISSUE TITLE
Compatibility for Aurum's More Blocks

### ISSUE THREAD

**Issue by Blugori** [PianoManu/BlockCarpentry#19]
Hi !
I am using blockcarpentry 1.16.2-0.3.4 and Aurum's more block 1.16.3-0.1.0, and the bamboo block from this last mod cannot be used on the carpentry blocks ;( 
I tested few different blocks from AMB and this is the only one that wont work
![2020-10-28_17 44 25](https://user-images.githubusercontent.com/66573974/97469082-49b5fa00-1946-11eb-8322-06c62818baed.png)

**Comment by Blugori** [comment]
The bamboo block is a rotatable block,  like logs and hay bale

**Comment by PianoManu** [comment]
Hmmm. What does happen, when you right-click a frame block? Nothing? Or does the frame become invisible

**Comment by Blugori** [comment]
Nothing happen when I right click a frame block with a bamboo block

**Comment by PianoManu** [comment]
Okay, I have an idea how to solve it, but I have very few time right now, due to my studies

**Comment by Blugori** [comment]
No problem !

**Comment by PianoManu** [comment]
It should be working with the newest version (which is already some weeks old but I forgot about this issue). The feature for rotating blocks will come in the next update (hopefully), so I'll close this issue for now. Regards, Manu
