### ISSUE TITLE
BlockCarpentry slabs horizontal placement

### ISSUE THREAD

**Issue by Ridanisaurus** [PianoManu/BlockCarpentry#23]
BlockCarpentry slabs completely disregard the standard Vanilla way of slab placement. If you are trying to place them on the side of a block they go vertically, making it a nightmare to place them horizontally where it will require a block beneath it to have it at the bottom, or a block on top to have it places on the top half of a block.

Would be nice to have one of the tools rotate the block vertically instead of having it as the default placement method while keeping the standard vanilla slab placement behavior as the default.

**Comment by PianoManu** [comment]
I'll fix it asap

**Comment by PianoManu** [comment]
Forgot to close this issue. I did fix this a long time ago... Slab placement does work like in vanilla now. By pressing shift, you can place slabs vertically
