### ISSUE TITLE
1.16.4 Compatibility (Very easy fix)

### ISSUE THREAD

**Issue by NillerMedDild** [PianoManu/BlockCarpentry#24]
Hi there o/ Current BlockCarpentry cannot be installed via the CurseForge launcher in 1.16.4 instances. If you check the box for 1.16.4 in the file settings, it will be installable.

**Comment by PianoManu** [comment]
Thanks for the hint, I changed the file settings. Sadly, I can't verify right now if it really works for 1.16.4 due to much stress at my university, but I'll dedicate myself to that as soon as possible.
Regards, Manu

**Comment by NillerMedDild** [comment]
No worries and no need, it works on 1.16.4, we've been using it for weeks :)
Hope Uni goes well!

**Comment by PianoManu** [comment]
Thank you very much!
