### ISSUE TITLE
[1.16.4] Compatible Minecraft Versions Incorrect

### ISSUE THREAD

**Issue by NillerMedDild** [PianoManu/BlockCarpentry#26]
Version 0.3.5 cannot be run on Minecraft 1.16.4, as it appears the compatible versions are listed incorrectly.

**Comment by PianoManu** [comment]
Weird... thanks for reporting

**Comment by PianoManu** [comment]
Found the problem. For some weird reason, changing `versionRange="[1.16.1,1.16.2,1.16.3,1.16.4]"` to `versionRange="[1.16.1,)"` in the mods.toml makes it work. I made the mistake of thinking "Oh, it worked with `versionRange="[1.16.1,1.16.2,1.16.3]"`, so I'll just add `1.16.4` and it'll work. I don't have to test that again"

Apparently, it stops working, when I add a fourth argument wtf...

**Comment by PianoManu** [comment]
Alright, I've tested it, now it really works for 1.16.4. I archived the other version and uploaded a new one (0.3.5a). I'm sorry for the inconvenience

**Comment by NillerMedDild** [comment]
No worries, thanks!
