### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by Imrald** [PianoManu/BlockCarpentry#27]
https://pastebin.pl/view/6ab70d1c

**Comment by Imrald** [comment]
Ehy man, just wanted to say that the crash is not happening anymore, even if i don't know how.
Sorry to not knowing the fix.
For now, have a nice day and again happy Holidays

**Comment by PianoManu** [comment]
Seems like the 0.3.5a has more bugs than I expected... So everything is working fine now?

**Comment by Imrald** [comment]
Yes, no more crashes due to your mod 😊
I didn't know if it was me that had to close the issue or you. Let me know and I'll proceed.
Hope you're doing well, have a nice day!

**Comment by PianoManu** [comment]
Alright, no problem. Thanks, you too!
