### ISSUE TITLE
[Suggestion] Rotate textures in framed blocks

### ISSUE THREAD

**Issue by tanyan-tanyan** [PianoManu/BlockCarpentry#29]
Would it be possible to create a new tool which lets you rotate textures in 90 degree iterations?
My friend is decorating the inside of his house using framed blocks and as you can see, there are logs facing one way and then the other. The ones highlighted in red are not turned the right way and I believe this can't be changed.

![javaw_LBSZw3qQss](https://user-images.githubusercontent.com/68793071/106678594-f4c3f880-65b2-11eb-8abe-7a3f1783d979.png)

**Comment by PianoManu** [comment]
That's a good idea. Thanks for the feedback :)

**Comment by PianoManu** [comment]
![2022-05-31_12 39 06](https://user-images.githubusercontent.com/59123244/171155236-0ad41475-d398-478f-9606-b474164ca659.png)

It works now :)

Use logs on illusion blocks (or in this case, a furnace), and right-click with the texture wrench to change the rotation of the model. This should already work on the latest 1.16 and 1.18 version, as I implemented this feature some time ago, but forgot to close this issue 😄

Again, thanks for your suggestion!
Regards, Manu
