### ISSUE TITLE
Glowstone does nothing?

### ISSUE THREAD

**Issue by appcreatorguy** [PianoManu/BlockCarpentry#30]
I'm trying to make a block emit light, but the light level wont change. I'm playing on 1.16.3, on the latest version at the time of posting. This affects all framed blocks, as far as I can tell. Please help, I'm really liking this mod so far!

EDIT: The same thing also happens with coal.

https://user-images.githubusercontent.com/14041410/107055559-552c8300-67c9-11eb-8a7d-ebb42b47e837.mp4

**Comment by PianoManu** [comment]
Sorry for the late response. I've had a lot of stress in my exam phase lately...

I tried to recreate the problem, but it works fine for me...
Did this problem occur in a modpack?

https://user-images.githubusercontent.com/59123244/113557235-fbe0a480-95fd-11eb-9e43-4fcf2a6c0654.mp4

**Comment by appcreatorguy** [comment]
No worries, yes, I'm using a modpack I'm developing, here is the curseforge [link.](https://www.curseforge.com/minecraft/modpacks/conceive)
<details>
  <summary>And the modlist:</summary>
  


    AppleSkin
    Building Wands
    Clumps
    Controlling
    Crafting Tweaks
    Create
    Fast Leaf Decay
    FTB Ultimine
    INMIS
        JEI
        Klee Slabs
        Mouse Tweaks
        Neat
        Sleeping Bags
        Terraforged
        Toolbelt
        Xaero's Minimap and Worldmap
        Polymorph
        Chicken Chunks
        Decorative Blocks
        Crafting Station
        Forgiving Void
        Performant
        Windowlogging
        Better Advancements
        Easy Villagers
        Easy Piglins
        Easy Elytra Takeoff
        Uppers
            Light Overlay
            Macaw's Bridges, Doors, Trapdoors, Windows, Roofs
            NetherPortalFix
            Client Tweaks
            Enchantment Descriptions
            Applied Energistics 2
            Nature's Compass
            Curios API
            Sophisticated Backpacks
            Curious Elytra
            Dank Storage
            Skiing
            Create Crafts & Additions
            Create Plus
            Dash
            Leap
            Step
            Extra Boats
            Simple Planes
            Cosmetic Armour Reworked
            Farmer's Delight
            Minecraft Capes Mod
            Refined Storage
            Refined Pipes
            Refined Storage Addons
            Simple Magnets
            Extra Disks
            ExtraStorage
            CraftPresence
            Just Enough Resources
            Just Enough Beacons
            Just Enough Professions
            Just Enough Piglin Bartering
                Advanced Finders
                BlockCarpentry
                Woodcutter
                Quark
                The One Probe
                Joy of Painting
                Pane In the Glass
                Fairy Lights
                Extended Lights
                Waystones
                Towers of the Wild


  
</details>

**Comment by PianoManu** [comment]
Seems like an OptiFine problem. I just installed OptiFine, and the lighting does not work anymore. I guess, there's not much I can do about that :(

**Comment by PianoManu** [comment]
Well, it's not the first time that there are problems between OptiFine and BlockCarpentry, because OptiFine changes the way, how blocks are rendered, and BlockCarpentry uses the "classic" way 🤷‍♂️ 
So for now, I won't to anything to change that, because I also realized, that the lighting works, when you make the block emit light (without having OptiFine installed) and then install/start the modpack with OptiFine

**Comment by appcreatorguy** [comment]
Ok, I'll try it without optifine. Thanks!
