### ISSUE TITLE
[Suggestion] New way to place slopes

### ISSUE THREAD

**Issue by tanyan-tanyan** [PianoManu/BlockCarpentry#31]
![javaw_s9jPFwViNY](https://user-images.githubusercontent.com/68793071/107723667-afea4100-6cd9-11eb-8c6c-04bb13b35d20.png)

![YY93a5m](https://user-images.githubusercontent.com/68793071/107723840-356df100-6cda-11eb-99c9-15f5a45dfca0.png)

This is the one slope orientation that doesn't seem to have been carried over from the predecessors, is it possible to implement this in the future? (There are also corners that will come from this orientation, however I couldn't find pictures of these)

**Comment by PianoManu** [comment]
That's a good idea. But to be honest, implementing slopes was really annoying and complicated, because of the triangluar textures, so I won't do that now. Maybe later, if I have some time. Nevertheless, many thanks for your feedback!
Regards, Manu

**Comment by Trinsec** [comment]
This is indeed what I was missing big-time and my #1 reason to use Carpenter's Blocks back then. Came to check if this issue existed yet. 😁
Hope you'll have the time someday! Good luck!

**Comment by PianoManu** [comment]
Yeah it's stil on my to-do list

**Comment by PianoManu** [comment]
Sooo after almost 2,5 years, I found time and implemented a mechanism similar to the "collapsing" mechanism from Carpenter's Blocks, which allows for moving corners of a block using the chisel (currently 1.19 only, will be backported tho). So you can now make your own slopes according to your desire 😄

Regards, Manu
