### ISSUE TITLE
Server and Client Crashes when connecting any pipe to framed chest

### ISSUE THREAD

**Issue by Saenaria** [PianoManu/BlockCarpentry#33]
Also does this with Mekanism but only server side and I don't have access to those logs.
[crash-2021-03-10_12.45.37-client.txt](https://github.com/PianoManu/BlockCarpentry/files/6117883/crash-2021-03-10_12.45.37-client.txt)

**Comment by ShamblerDK** [comment]
I might be able to help with that:
https://pastebin.com/ar9U1ef5

**Comment by PianoManu** [comment]
Thanks for reporting. Actually it's the same bug as #32 - it seems, you can't connect hoppers or pipes or anything that extracts items from chests. I'll try to fix it. Thanks for reporting!

**Comment by PianoManu** [comment]
Same error as #32 - same solution as #32:  I'll release the fixed version today in the afternoon or tomorrow (0.3.5b). Thanks for reporting and sorry for the inconvenieces

**Comment by PianoManu** [comment]
I just released the fixed version [0.3.5b](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3264543). The problem shouldn't occur anymore, hopefully. At least I can't recreate it anymore...
