### ISSUE TITLE
cannot add block to frame door/gate/trapdoor when they are placed next to same type of frame block

### ISSUE THREAD

**Issue by Legion7766** [PianoManu/BlockCarpentry#34]
When I place framed trapdoors that are next to each other and therefore are both activated when you click on one i can no longer apply a block to either framed trapdoor to change their look.
![trapdoor](https://user-images.githubusercontent.com/33643299/112421337-d8178780-8cfc-11eb-9ed5-1aa18ff22673.png)

**Comment by PianoManu** [comment]
I'm sorry, I can't recreate that problem. I tried placing them in a row, around a block and on top of each other, but opening/closing and inserting blocks does work fine for me. Could you maybe explain the problem a bit more? And which modpack were you using, when the problem occured?

**Comment by Legion7766** [comment]
![image](https://user-images.githubusercontent.com/33643299/116900818-cd56e900-abfe-11eb-80c9-587aa0e7879a.png)
![image](https://user-images.githubusercontent.com/33643299/116900881-e2337c80-abfe-11eb-8689-a8102cf11650.png)

hopefully this helps sorry don't have a lot of time right now myself to look into this right now.  It might be another mod that is interfering but when i place two trap doors side by side like on the left in the picture they just open an close together and i cannot put a block on them while if the trapdoor is solo i can add the block to it.

**Comment by PianoManu** [comment]
No further information regarding this problem... I'll close this issue now. Feel free to reopen this issue, if you can provide additional information
