### ISSUE TITLE
Trapdoors Silent

### ISSUE THREAD

**Issue by DerekM07** [PianoManu/BlockCarpentry#4]
Trapdoors make no sound when opened/closed. (v0.7.1 for MC 1.15.2)

**Comment by PianoManu** [comment]
Thanks for reporting. I'll fix it asap

**Comment by PianoManu** [comment]
> I'll fix it asap
Yeah....
So I have to add the "help needed" label, because I copied the code from the vanilla TrapDoorBlock, where I think that it makes the sound, but nothing happens.... The code is as following:
`if (state.get(OPEN)) {
                    state = state.with(OPEN, false);
                } else {
                    state = state.with(OPEN, true);
                }
                world.setBlockState(pos, state, 2);
                if (state.get(WATERLOGGED)) {
                    world.getPendingFluidTicks().scheduleTick(pos, Fluids.WATER, Fluids.WATER.getTickRate(world));
                }
                this.playSound(player, world, pos, state.get(OPEN));`
Any help is appreciated

**Comment by WenXin20** [comment]
It looks like the sound comes from the `ActionResultType onBlockActivated()` in the trapdoor class, maybe check there?

**Comment by PianoManu** [comment]
Yeah, I copied and pasted the code from the trapdoor class, so I wonder, why it is not playing the sound event - the other stuff (opening, closing), which happens in the same if statement, works fine

**Comment by PianoManu** [comment]
Alright, it is working now. I don't know why, but when changing `world.playEvent(player , 1013, pos, 0);` to `world.playEvent(null, 1013, pos, 0);`, it suddenly worked. In this line, the `1013` determines the sound (which is the Trapdoor-open - sound). I fixed it, and it will be published in version 1.16.2/1.16.3-0.3.4. I'll close this issue now

**Comment by DerekM07** [comment]
@PianoManu Thanks for fixing the trapdoors, but I have to deliver bad news that the fence gates have the same problem. No opening or closing sounds. Tested w the current version of the mod, in MC 1.16.4.
