### ISSUE TITLE
NBT error with Copy Paste gadget from building gadgets

### ISSUE THREAD

**Issue by Zaecus** [PianoManu/BlockCarpentry#40]
When using the copy paste gadget to paste a structure with BlockCarpentry blocks in it, the world crashes and then crashes every time I try to load that world. Removing the BC blocks allows for a successful copy and paste. I have been told the BC blocks are not getting the right NBT data, and I do not know if this is an issue with this mod or that one or if the two of you need to figure that out so I'm reporting it both places and including a crash report.

[crash-2021-06-11_08.08.01-client.txt](https://github.com/PianoManu/BlockCarpentry/files/6638600/crash-2021-06-11_08.08.01-client.txt)

**Comment by PianoManu** [comment]
Sorry for not answering earlier, I'm having a lot of work right now. That's a known bug and I already fixed it (same error as in #39), it will be published with version 0.3.7 sometime soon. 
Regards, Manu

**Comment by PianoManu** [comment]
0.3.7 is out, so I'm closing this issue
