### ISSUE TITLE
Frame Chest naming

### ISSUE THREAD

**Issue by MyNamesRaph** [PianoManu/BlockCarpentry#42]
Frame Chests and Illusion Chests do not keep and display their custom name after placing it into the world like vanilla inventories do. (Version 0.3.6)

**Comment by PianoManu** [comment]
It's working now, finally!!! I'll release it with the next major update :)
Thanks for reporting and sorry for not responding, I was very busy with my studies...
Regards, Manu
![2021-08-18_20 28 52](https://user-images.githubusercontent.com/59123244/129952578-a6775967-cde6-4bf1-9835-e0088549754b.png)

**Comment by PianoManu** [comment]
Fixed with [0.4.0](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3441935)

Again, thanks for reporting! :)
