### ISSUE TITLE
Frame Blocks crashing when broken with a block in them.

### ISSUE THREAD

**Issue by Rensik** [PianoManu/BlockCarpentry#43]
This is the crash report.
https://paste.gg/p/anonymous/571098c1313f4dbd9be4e06b17b19c3d

BlockCarpentry 0.3.6, Forge 32.1.36

The blocks used on the frame were a Factory Block from Chisel(still in alpha) and then an Oak Log to verify.

ps. does not crash when the frame is empty.

pps. does not crash when the block is removed.

**Comment by PianoManu** [comment]
It's working now... I've tested with [BlockCarpentry 0.3.9](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3430443) and [Chisel 2.0.0](https://www.curseforge.com/minecraft/mc-mods/chisel/files/3367011)
![2021-08-18_18 03 24](https://user-images.githubusercontent.com/59123244/129932362-e8c45bdc-9dbc-40f7-b08f-3da6d083a381.png)
