### ISSUE TITLE
Emerald block texture

### ISSUE THREAD

**Issue by Sunekaer** [PianoManu/BlockCarpentry#45]
With latest update blockcarpentry-1.16-0.3.7.jar
Emerald block texture has changed.
![image](https://user-images.githubusercontent.com/18720460/129448763-f5c995a6-521b-4a86-8c1d-a4e0d6204d7b.png)

**Comment by PianoManu** [comment]
Oh nooo I did it again.... Accidentially included the debug texture in the release...  Sorry

Thanks for reporting!
Regards, Manu

**Comment by PianoManu** [comment]
Should be fixed with [0.3.8](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3425242) :)
