### ISSUE TITLE
0.3.9 re-adds the emerald block texture

### ISSUE THREAD

**Issue by aaronhowser1** [PianoManu/BlockCarpentry#48]
![image](https://user-images.githubusercontent.com/15698722/129939377-4b04e0d8-a577-4fd3-8731-129412e34d0a.png)

**Comment by PianoManu** [comment]
Ah nooo why do i make this mistake every time ... thanks for reporting...

**Comment by PianoManu** [comment]
I archived 0.3.9 and uploaded [0.3.10](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3430582), because I also implemented the crimson/warped-overlay feature today.
Again, thanks for reporting!
Regards, Manu
