### ISSUE TITLE
Blacklist/Whitelist Support

### ISSUE THREAD

**Issue by WenXin20** [PianoManu/BlockCarpentry#5]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Block Carpentry v0.7.2`

Adding a blacklist/whitelist could be useful, such as to prevent blocks that would normally crash the game from being used.
I got a crash after right-clicking the Frame Slab with a block from the Cubic Villager mod, so adding a blacklist could help prevent these. A blacklist that can use tags and wildcards (such as `cubicvillager:*`) could be helpful.
[Crash Report](https://gist.github.com/WenXin20/4316a754f9a4babafe2299149b1609ea)

**Comment by PianoManu** [comment]
I found a slightly different solution. The mod now simply refuses to bake a model, when the concerning block does not have a model (e.g. vanilla chests do not have a model but a TER), so you only see the boundary box and get a message, that the block can't be displayed. It's not very fancy, but it should be enough, right? Thanks for reporting!
Regards, Manu

**Comment by WenXin20** [comment]
Yes, that should be fine. Thanks again!

**Comment by PianoManu** [comment]
I did not encounter this bug anymore, so I guess it is fixed...
