### ISSUE TITLE
Slab Frame Block with Concrete crash server

### ISSUE THREAD

**Issue by adraios** [PianoManu/BlockCarpentry#52]
Path followed for crash:
1. Placed bottom half slab frame block
2. Right clicked with magenta concrete on slab frame block
3. Server crashed

Here is the crash report:
[crash-2021-08-27_15.19.22-server.txt](https://github.com/PianoManu/BlockCarpentry/files/7066818/crash-2021-08-27_15.19.22-server.txt)

**Comment by PianoManu** [comment]
Fixed with [0.4.0](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry/files/3441935)
