### ISSUE TITLE
Crash when breaking stairs/slabs with Immersive Engineering steel block

### ISSUE THREAD

**Issue by kill05** [PianoManu/BlockCarpentry#58]
The title kinda explains it, I'm getting this error that causes my game to crash when i break a stair or slab with an IE steel block

https://pastebin.com/Z4ih1mYe

Edit: i've just noticed that it doesn't happen everytime, but quite often

**Comment by PianoManu** [comment]
This is the same problem as #39. You are using an old version (0.3.6). Try using the newest version (0.4.0) or ask the developer of the modpack to update to the newest version.
Regards, Manu
