### ISSUE TITLE
Glass Crash

### ISSUE THREAD

**Issue by WenXin20** [PianoManu/BlockCarpentry#6]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Block Carpentry v0.7.2`

I right-clicked a glass block on a frame or illusion slab and then my game crashed. I also cannot place modded glass into the frame blocks (this does not crash).
[Crash Report](https://gist.github.com/WenXin20/8333f0a1d3c45e6b4c31289c2b15403e)

**Comment by PianoManu** [comment]
Thanks for reporting, this bug has the same origin as #5 (at least that's what I can tell from the crash report you attached there), it should be fixed by now

**Comment by WenXin20** [comment]
Thanks!

**Comment by PianoManu** [comment]
And I forgot to answer the "modded-glass" part. I intentionally set it up so that other glass wouldn't work, but I hope I can get modded glass to work later 🤷
For now, I'll close this issue, as the original bug should be fixed by now
