### ISSUE TITLE
Client freezes when taking too many stacks from Frame Chests

### ISSUE THREAD

**Issue by Deaymon** [PianoManu/BlockCarpentry#64]
This is an issue that has happened many times on the Vault Hunters modpack server I play with friends. To be exact, the mod version this modpack uses is "blockcarpentry-1.16-0.4.0".

Any time anyone takes too many stacks from a frame chest too quick (via dragging around them with inventory tweaks), their client freezes completely with no other choice but forcequit the game.
A thing that I've noticed is that it seems to be client-side only. When this happens to the person that is opening the server to LAN, their client freezes as usual, but anyone else that is connected to the server can play normally as if nothing happened.

Don't know what else to do to pinpoint the problem, since the freeze means having to close the client and reopen it, which takes 10 minutes easily every time.

**Comment by PianoManu** [comment]
Thanks for reporting! I almost expected issues with the chest cause I still have problems understanding how the UpdatePacket and NetworkManager work together. Back then I just kept trying until it somehow worked and so far there haven't been any reported problems with it, even though the version has been out for quite a while.

Did you have any other mods installed? Because I can't recreate the issue using inventory tweaks...

**Comment by PianoManu** [comment]
https://user-images.githubusercontent.com/59123244/166225283-c9f6864f-a08f-4cc7-9682-3b425728680a.mp4

Works fine for me

**Comment by Deaymon** [comment]
I do have other mods installed, yes. The Vault Hunters modpack to be exact. But that's 100+ mods, unfortunately, so the best thing I can offer is the list of mods. The thing is, this only seems to happen with frame chests. Also, we have the theory that it happens when we try to empty a stack of items from a chest while we have an already full inventory.

Here's the list of mods:
AppleSkin (by squeek502)
Applied Energistics 2 (by AlgorithmX2)
Archer's Paradox (by TeamCoFH)
Architectury API (Forge) (by shedaniel)
AutoRegLib (by Vazkii)
BlockCarpentry (by PianoManu)
Bookshelf (by DarkhaxDev)
Botania (by Vazkii)
Building Gadgets (by Direwolf20)
Camera Mod (by henkelmax)
Clumps (by Jaredlll08)
CoFH Core (by TeamCoFH)
Comforts (Forge) (by TheIllusiveC4)
Compressium (by DinnerBeef)
Controlling (by Jaredlll08)
Cooking for Blockheads (by BlayTheNinth)
Corpse (by henkelmax)
CraftTweaker (by Jaredlll08)
Create (by simibubi)
CreateTweaker (by Jaredlll08)
Cucumber Library (by BlakeBr0)
Curios API (Forge) (by TheIllusiveC4)
Dank Storage (by tfarecnim)
Dark Utilities (by DarkhaxDev)
Decorative Blocks (by stohun)
DimStorage (by 3divad99)
Easy Villagers (by henkelmax)
Ender Mail (by Chaosyr)
Engineer's Decor (by wilechaote)
Entity Detectors (by Commoble)
Environmental Materials (by ValkyrieofNight)
FTB Backups (Forge) (by FTB)
FTB Library (Forge) (by FTB)
Fairy Lights (by pau101)
FastWorkbench (by Shadows_of_Fire)
Flux Networks (by sonar_sonic)
Flywheel (by jozufozu)
Framed Compacting Drawers (by Eutropium)
Gauges and Switches (by wilechaote)
Hwyla (by TehNut)
ISpawner (by Iskall85_Dev)
Immersive Engineering (by BluSunrize)
Industrial Foregoing (by Buuz135)
Inventory Tweaks Renewed (by David1544)
Iron Chests (by ProgWML6)
Iron Furnaces [FORGE] (by XenoMustache)
Iron Jetpacks (by BlakeBr0)
Iskall Utilities (by Iskall85_Dev)
JEI Integration (by SnowShock35)
JEITweaker (by Jaredlll08)
Just Enough Items (JEI) (by mezz)
Just Enough Resources (JER) (by way2muchnoise)
Lollipop (by owmii)
Macaw's Bridges (by sketch_macaw)
Macaw's Doors (by sketch_macaw)
Macaw's Furniture (by sketch_macaw)
Macaw's Roofs (by sketch_macaw)
Macaw's Windows (by sketch_macaw)
Masonry (by Shadowclaimer)
McJtyLib (by McJty)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Metal Barrels (by tfarecnim)
Mining Gadgets (by Direwolf20)
MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)
Modular Routers (by desht_08)
Morpheus (by Quetzi)
Mouse Tweaks (by YaLTeR)
Moving Elevators (by SuperMartijn642)
MrCrayfish's Furniture Mod (by MrCrayfish)
Neon Craft Mod (by Polyvalord)
Oh The Biomes You'll Go (by AOCAWOL)
Open Loader (by DarkhaxDev)
OpenBlocks Elevator (by vsngarcia)
Patchouli (by Vazkii)
Placebo (by Shadows_of_Fire)
Platforms (by ShetiPhian)
Powah! (by owmii)
Pretty Pipes (by Ellpeck)
Quark (by Vazkii)
RFTools Base (by McJty)
RFTools Builder (by McJty)
RFTools Power (by McJty)
RFTools Storage (by McJty)
RFTools Utility (by McJty)
Ranged Pumps (by raoulvdberge)
Refined Storage (by raoulvdberge)
Refined Storage Addons (by raoulvdberge)
Refined Storage: Requestify (by Buuz135)
Runelic (by DarkhaxDev)
Selene Lib (by MehVahdJukaar)
ShetiPhianCore (by ShetiPhian)
Simply Backpacks (by Flanks255)
Simply Light (by Flanks255)
Snad (by lazynessmind)
Storage Drawers (by Texelsaur)
Storage Overhaul (by henkelmax)
SuperMartijn642's Core Lib (by SuperMartijn642)
Supplementaries (by MehVahdJukaar)
Thermal Expansion (by TeamCoFH)
Thermal Foundation (by TeamCoFH)
Titanium (by Buuz135)
Torchmaster (by xalcon)
ToroHealth Damage Indicators (by ToroCraft)
Trash Cans (by SuperMartijn642)
U Team Core (by HyCraftHD)
Useful Railroads (by HyCraftHD)
ValkyrieLib (by ValkyrieofNight)
Vault Hunters - Official Mod (by Iskall85_Dev)
Waddles (by Girafi)
Waystones (by BlayTheNinth)
XNet (by McJty)
Xaero's Minimap (by xaero96)
Xaero's World Map (by xaero96)

**Comment by vgrynch** [comment]
Seems works as expected in 1.19.2, with a lot of mods (300+ pages in JEI). I have also tried large numbers of items with large NBT data in them and all worked. Might be related to memory leaks, Tweaks bug itself, or some other container mods involved.

**Comment by PianoManu** [comment]
> Seems works as expected in 1.19.2, with a lot of mods (300+ pages in JEI). I have also tried large numbers of items with large NBT data in them and all worked. Might be related to memory leaks, Tweaks bug itself, or some other container mods involved.

So I'm gonna use this response to close this issue. Thank you @vgrynch for checking! I'm missing some time to do it all by myself, so you helped me a lot! :)
