### ISSUE TITLE
[1.19] Crash on load possibly due to breaking changes in Forge

### ISSUE THREAD

**Issue by ProsperCraft** [PianoManu/BlockCarpentry#65]
https://gist.githubusercontent.com/ProsperCraft/8962d2c9c57743b5bec51936adf416b2/raw/dc445b07d745aaf5a2e09fc72a087ab9211aef06/gistfile1.txt
blockcarpentry-1.19-0.0.1.0

**Comment by PianoManu** [comment]
Sorry for the late response... Fixed it in update 0.1.1.0 for 1.19
