### ISSUE TITLE
Frame Carpet recipe error?

### ISSUE THREAD

**Issue by GenderedHuman** [PianoManu/BlockCarpentry#66]
https://imgur.com/a/rsYUUb2

I'm assuming the minecraft tag changed between one of the versions? (it's now "wool_carpets" I believe)

I am using minecraft 1.19.2 and mod version blockcarpentry-1.19-0.1.1.0

**Comment by PianoManu** [comment]
Thanks for reporting. I will fix this asap! Did you encounter any other recipe bugs?

Regards, Manu

**Comment by GenderedHuman** [comment]
I did not, every other recipe seemed normal in the JEI mod that I saw!
Love the mod btw <3

**Comment by PianoManu** [comment]
Alright, thank you very much and thanks for your nice words! I appreciate that! :)

Regards, Manu
