### ISSUE TITLE
Mod Conflict with Dramatic Doors

### ISSUE THREAD

**Issue by LopyLuna** [PianoManu/BlockCarpentry#67]
**Crash Log**
[crash-2022-12-24_07.18.38-fml.log](https://github.com/PianoManu/BlockCarpentry/files/10298871/crash-2022-12-24_07.18.38-fml.log)

**Mods**
![image](https://user-images.githubusercontent.com/100169742/209443846-d6aeba11-f320-477f-8210-876e38c02276.png)

**Error while load up**
![image](https://user-images.githubusercontent.com/100169742/209443868-48f8f412-4a27-4c62-9bee-066b5a44b6f2.png)

Minecraft - 1.18.2
Forge - 40.1.92

I Also Reported the same for Dramatic Doors

**Comment by Kitteh6660** [comment]
That is on my mod's side, this will be fixed.

**Comment by LopyLuna** [comment]
sweet

**Comment by Kitteh6660** [comment]
Now fixed as of mod version 2.1.8.
