### ISSUE TITLE
Missing Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [PianoManu/BlockCarpentry#7]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Block Carpentry v0.7.2`

Frame/Illusion slabs are missing the waterlogging ability. 
It would also be nice to see waterlogging added for the frame full blocks, doors, pressure plates, and buttons, although that is not a vanilla feature.

**Comment by PianoManu** [comment]
Yup, and you know why? Because I'm stupid. I'm fixing that right now and it will be included in the next update

**Comment by PianoManu** [comment]
I will think about adding waterlogging for doors, pressure plates and buttons, but I'm not sure if this makes sense, when they are waterloggable but their vanilla counterparts are not. This might lead to unwanted circumstances, so Idk... I'll leave this thread open

**Comment by WenXin20** [comment]
Thanks! I wasn't sure if it was needed for those other blocks either, but thought that I would mention it.

**Comment by WenXin20** [comment]
I've tested the slab, but I've noticed that if I sound the sides of the slab with blocks, then waterlog the slab, and then break one of the blocks next to the slab, the water will not flow from.  I'm not sure why since the method `updatePostPlacement` is being used.

**Comment by PianoManu** [comment]
Thanks for telling me, I forgot to override the `updatePostPlacement` method. Does this problem occur with any other blocks?

**Comment by WenXin20** [comment]
Did a bit more testing, the Frame Block, Frame Fence Gate, & Frame Chest removes water when placed (most noticeable when there is only one water block. The Frame Fence Gate also doesn't update post placement.

**Comment by PianoManu** [comment]
Yup, I fixed the gate and chest yesterday. I also changed the frame block boundary box, so water can now flow. I hope this fixes it

**Comment by WenXin20** [comment]
Thanks, I'll see if I can give it a try later today.

**Comment by PianoManu** [comment]
I've tested all frame blocks and it works correctly now (illusion blocks work the same way, so I didn't test them extra). I'll mark this issue as fixed and close it now
