### ISSUE TITLE
Overlay on the bottom part of the 2-block wall does not apply

### ISSUE THREAD

**Issue by vgrynch** [PianoManu/BlockCarpentry#76]
I know this might be not diable because the bottom parts of 2-block walls have different state numbers and there are a lot of combinations of states if account all of the states. However, giving it a shot...

![image](https://github.com/PianoManu/BlockCarpentry/assets/46818018/f5a2cb72-2a8e-4802-b3ef-d8a671f608a2)

**Comment by PianoManu** [comment]
Oh that's weird... I did not realize this, I will look into it. Thanks for reporting!

**Comment by PianoManu** [comment]
![2023-09-18_20 41 33](https://github.com/PianoManu/BlockCarpentry/assets/59123244/52a7a921-2217-438d-9cc9-4bbd17ad7a9e)

It is finally working. Although the snow overlay is ugly on stacked walls...
Thanks again for reporting! :)

**Comment by vgrynch** [comment]
Thanks a lot!
