### ISSUE TITLE
Frame daylight detector - should detect light?

### ISSUE THREAD

**Issue by vgrynch** [PianoManu/BlockCarpentry#78]
Is the frame daylight detector decorative only? It does not work actually as a daylight detector (1.19.2).

**Comment by PianoManu** [comment]
Seems like I messed up the last update... I'm working on it

**Comment by PianoManu** [comment]
![2023-09-18_18 45 25](https://github.com/PianoManu/BlockCarpentry/assets/59123244/f7b1738e-411d-440a-8b86-2e5020bb211b)

It's working now and the power is updated during the daytime/nighttime. Will be included in the next release. Thanks again for pointing out! :)

Regards, Manu

**Comment by vgrynch** [comment]
Thanks!
