### ISSUE TITLE
[Server Crash]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by aking4125** [PianoManu/BlockCarpentry#81]
This was a strange one to figure out. After manually pulling mods out on the server side, found out that this mod seems to be the culprit. The bottom of the log file points to a different mod failing but reading it over, many mods are failing and the server loops on just one before it eventually stops. No crash report is created.

The server seems to continue to load and then stops. An issue pops up near the start of the server

`Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER`

I'm not confident this is the cause, but removing _**blockcarpentry-1.19.2-0.3.1.4.jar**_ from the modlist on the server only allows the server to load. Could be some type of conflict? Any ideas?

[debug.log](https://github.com/PianoManu/BlockCarpentry/files/13819854/debug.log)
[latest.log](https://github.com/PianoManu/BlockCarpentry/files/13819855/latest.log)

**Comment by PianoManu** [comment]
Uhhh... I tried to add cross-compatibility between Apotheosis and Blockcarpentry in regards to the Eterna-Stuff when a frame block is given enchanting power. I guess I forgot to check for whether it happens on server or client side ...
I'll look into it. For now please use 0.3.1.3 instead. Sorry for the inconvenience

**Comment by PianoManu** [comment]
Problem should be fixed now in version 0.3.1.5 (which is uploading right now on curseforge). Thanks again for reporting!
Regards, Manu
